# Generated by Django 3.2.9 on 2021-11-22 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('personal_no', models.CharField(max_length=11, unique=True)),
                ('birth_place', models.CharField(max_length=120)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('f', 'female'), ('m', 'male')], max_length=20)),
                ('photo', models.ImageField(upload_to='images/')),
                ('drivers_license', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='card_data.department')),
            ],
        ),
    ]
